# Site settings
title: Incognitech
email: desaiuditd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of an Incognito Mind :P
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://desaiuditd.github.io" # the base hostname & protocol for your site
twitter_username: desaiuditd
github_username:  desaiuditd

# Build settings
markdown: kramdown
